name: Build

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Install JDK 11
        uses: actions/setup-java@v1.4.3
        with: 
          java-version: 11
      - name: Run Maven build
        run: mvn clean install
